CREATE TABLE IF NOT EXISTS "Films" (
    "FilmID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100)   NOT NULL,
    "Description" varchar(200),
    "ReleaseDate" date,
    "Duration" int,
    "Rating" int,
    CONSTRAINT "pk_Films" PRIMARY KEY (
        "FilmID"
     )
);

CREATE TABLE IF NOT EXISTS "Users" (
    "UserID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Login" varchar(50)   NOT NULL,
    "Name" varchar(100),
    "Email" varchar(100),
    "Birthday" date,
    CONSTRAINT "pk_Users" PRIMARY KEY (
        "UserID"
     )
);

CREATE TABLE IF NOT EXISTS "FilmLikes" (
    "FilmID" int   NOT NULL,
    "UserID" int   NOT NULL,
    CONSTRAINT "pk_FilmLikes" PRIMARY KEY (
        "FilmID","UserID"
     )
);

CREATE TABLE IF NOT EXISTS "Friends" (
    "UserID" int   NOT NULL,
    "FriendID" int   NOT NULL,
    "Status" boolean,
    CONSTRAINT "pk_Friends" PRIMARY KEY (
        "UserID","FriendID"
     )
);

CREATE TABLE IF NOT EXISTS "Genre" (
    "GenreID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100)   NOT NULL,
    CONSTRAINT "pk_Genre" PRIMARY KEY (
        "GenreID"
     )
);

CREATE TABLE IF NOT EXISTS "FilmsGenre" (
    "FilmID" int   NOT NULL,
    "GenreID" int   NOT NULL,
    CONSTRAINT "pk_FilmsGenre" PRIMARY KEY (
        "FilmID","GenreID"
     )
);

CREATE TABLE IF NOT EXISTS "RatingMPAA" (
    "RatingID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100) ,
    "Description" varchar(200),
    CONSTRAINT "pk_RatingMPAA" PRIMARY KEY (
        "RatingID"
     )
);

ALTER TABLE IF EXISTS "Films" ADD CONSTRAINT IF NOT EXISTS "fk_Films_Rating" FOREIGN KEY("Rating")
REFERENCES "RatingMPAA" ("RatingID");

ALTER TABLE IF EXISTS "FilmLikes" ADD CONSTRAINT IF NOT EXISTS "fk_FilmLikes_FilmID" FOREIGN KEY("FilmID")
REFERENCES "Films" ("FilmID");

ALTER TABLE IF EXISTS "FilmLikes" ADD CONSTRAINT IF NOT EXISTS "fk_FilmLikes_UserID" FOREIGN KEY("UserID")
REFERENCES "Users" ("UserID");

ALTER TABLE IF EXISTS "Friends" ADD CONSTRAINT IF NOT EXISTS "fk_Friends_UserID" FOREIGN KEY("UserID")
REFERENCES "Users" ("UserID");

ALTER TABLE IF EXISTS "Friends" ADD CONSTRAINT IF NOT EXISTS "fk_Friends_FriendID" FOREIGN KEY("FriendID")
REFERENCES "Users" ("UserID");

ALTER TABLE IF EXISTS "FilmsGenre" ADD CONSTRAINT IF NOT EXISTS "fk_FilmsGenre_FilmID" FOREIGN KEY("FilmID")
REFERENCES "Films" ("FilmID");

ALTER TABLE IF EXISTS "FilmsGenre" ADD CONSTRAINT IF NOT EXISTS "fk_FilmsGenre_GenreID" FOREIGN KEY("GenreID")
REFERENCES "Genre" ("GenreID");